services:
  nginx:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      MY_GLOBAL_IP: host.docker.internal
      PORT: 7000
  test:
    image: nginx:1.27.2-alpine3.20-slim
    volumes:
      - ./test:/usr/share/nginx/html
    ports:
      - 7000:80
