name: CI pipeline

env:
  TZ: 'Asis/Tokyo'

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.github/CODEOWNERS'
      - '.gitignore'
      - 'LICENSE.md'
      - 'README.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Set up Java
        uses: actions/setup-java@v4.6.0
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'gradle'

      - name: Install gauge & plugin
        run: |
          curl -SsL https://downloads.gauge.org/stable | sh
          gauge install java

      - name: Test
        run: |
          ./gradlew clean integrationTest
